
#
## === JPA / Hibernate ===
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#
#
#spring.jpa.properties.hibernate.jdbc.batch_size=20
#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.connection-timeout=30000
#
### === Connection Pool (Optional: HikariCP is default) ===
##spring.datasource.hikari.maximum-pool-size=10
##spring.datasource.hikari.minimum-idle=5
#

spring.application.name=inventory-reservation-system

# === PostgreSQL (Render External DB) ===
spring.datasource.url=jdbc:postgresql://dpg-d8gf8dd8nd3s738uf1mg-a.oregon-postgres.render.com:5432/allo_db?sslmode=require
spring.datasource.username=allo_db_user
spring.datasource.password=hLPC0MJ67QpKoc7io7T99S5aXUijiW6U
#spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# === JPA / Hibernate ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.jdbc.batch_size=20

# === Hikari Pool ===
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000