#spring.application.name=inventory-reservation-system
## === Database Configuration ===
##spring.datasource.url=jdbc:mysql://localhost:3306/zorvyn_banking_app
##spring.datasource.username=root
##spring.datasource.password=Rohan@721422
##spring.datasource.url=jdbc:mysql://localhost:3306/allo_project?useSSL=false&serverTimezone=UTC
##spring.datasource.username=root
##spring.datasource.password=Rohan@721422
#spring.datasource.url=jdbc:mysql://mysql-330bed14-allo.aivencloud.com:25567/defaultdb?sslMode=REQUIRED
#spring.datasource.username=avnadmin
#spring.datasource.password=AVNS_C-014kegRNvi-sxMkQb
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#
## === JPA / Hibernate ===
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#
#
#spring.jpa.properties.hibernate.jdbc.batch_size=20
#spring.datasource.hikari.maximum-pool-size=10
#spring.datasource.hikari.connection-timeout=30000
#
### === Connection Pool (Optional: HikariCP is default) ===
##spring.datasource.hikari.maximum-pool-size=10
##spring.datasource.hikari.minimum-idle=5
#

spring.application.name=inventory-reservation-system

# === PostgreSQL (Render External DB) ===
spring.datasource.url=jdbc:postgresql://dpg-d8gf8dd8nd3s738uf1mg-a.oregon-postgres.render.com:5432/allo_db?sslmode=require
spring.datasource.username=allo_db_user
spring.datasource.password=hLPC0MJ67QpKoc7io7T99S5aXUijiW6U
spring.datasource.driver-class-name=org.postgresql.Driver

# === JPA / Hibernate ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.properties.hibernate.jdbc.batch_size=20

# === Hikari Pool ===
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=30000